baseurl = "http://www.vurt.co.uk/"
languageCode = "en-gb"
title = "vurt"

[params]
  AuthorName = "Giles Paterson"
  GitHubUser = "gilesp"
  SubTitle = "Ideas for things to do and how to (possibly) do them"    

[taxonomies]
  tag = "tags"
  category = "categories"
  project = "projects"

[indexes]
  project = "projects"
  idea = "ideas"

[[menu.main]]
  name = "Projects"
  identifier = "projects"
  url = "/projects"
  pre = "fa-cogs"

[[menu.main]]
  name = "Ideas"
  identifier = "ideas"
  url = "/ideas"
  pre = "fa-bolt"