baseurl = "https://vurt.co.uk/"
languageCode = "en-gb"
title = "vurt"
theme = "ghostwriter"
copyright = "Giles Paterson"
contentdir = "content"
publishdir = "public"
staticdir = "static"
builddrafts = false
canonifyurls = false
defaultExtension = "html"
pluralizeListTitles = true


[author]
    name = "Giles Paterson"
    profile = "https://plus.google.com/u/0/+GilesPaterson"

[params]
    AuthorName = "Giles Paterson"
    intro = true
    headline = "vurt.uk"
    description = "Ideas for things to do and how to (possibly) do them"
    github = "https://github.com/gilesp"
    twitter = "https://twitter.com/gilesp"
    stackoverflow = "https://stackoverflow.com/users/1514202/gilesp"
    gplus = "https://google.com/+GilesPaterson"
    linkedin = "https://uk.linkedin.com/in/gpaterson"

[taxonomies]
    tag = "tags"

[indexes]
    project = "projects"
    idea = "ideas"
    tag = "tags"

[blackfriday]
    plainIDAnchors = true

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/project/"
    pre = "fa-cogs"
    weight = 2

[[menu.main]]
    name = "Ideas"
    identifier = "ideas"
    url = "/idea/"
    pre = "fa-bolt"
    weight = 3
